{
  "files": [
    {
      "path": "main.py",
      "content": "#!/usr/bin/env python3\n# -*- coding: utf-8 -*-\n\n\"\"\"\n主程序文件 - 回答“你是做什么的”\n\"\"\"\n\nimport sys\nfrom config import load_config\n\ndef get_identity():\n    \"\"\"返回AI助手的身份描述\"\"\"\n    return \"我是一个AI助手，由OpenAI开发，旨在帮助用户解答问题、提供信息、生成文本和执行各种任务。\"\n\ndef main():\n    \"\"\"主函数\"\"\"\n    config = load_config()\n    \n    # 根据配置决定输出方式\n    if config.get('verbose', False):\n        print(\"详细模式启动...\")\n        print(f\"配置版本: {config.get('version', '1.0.0')}\")\n    \n    identity = get_identity()\n    print(identity)\n    \n    # 返回状态码\n    return 0\n\nif __name__ == \"__main__\":\n    sys.exit(main())\n"
    },
    {
      "path": "config.py",
      "content": "#!/usr/bin/env python3\n# -*- coding: utf-8 -*-\n\n\"\"\"\n配置文件 - 管理应用配置\n\"\"\"\n\nimport json\nimport os\n\ndef load_config(config_path: str = None) -> dict:\n    \"\"\"\n    加载配置文件\n    \n    Args:\n        config_path: 配置文件路径，默认为当前目录下的config.json\n    \n    Returns:\n        dict: 配置字典\n    \"\"\"\n    if config_path is None:\n        config_path = os.path.join(os.path.dirname(__file__), 'config.json')\n    \n    default_config = {\n        \"app_name\": \"IdentityApp\",\n        \"version\": \"1.0.0\",\n        \"verbose\": False,\n        \"language\": \"zh-CN\"\n    }\n    \n    try:\n        if os.path.exists(config_path):\n            with open(config_path, 'r', encoding='utf-8') as f:\n                user_config = json.load(f)\n                default_config.update(user_config)\n        else:\n            # 如果配置文件不存在，创建默认配置\n            with open(config_path, 'w', encoding='utf-8') as f:\n                json.dump(default_config, f, indent=4, ensure_ascii=False)\n    except Exception as e:\n        print(f\"加载配置文件失败: {e}\")\n    \n    return default_config\n"
    },
    {
      "path": "test_main.py",
      "content": "#!/usr/bin/env python3\n# -*- coding: utf-8 -*-\n\n\"\"\"\n测试文件 - 测试主程序功能\n\"\"\"\n\nimport unittest\nfrom main import get_identity, main\n\nclass TestIdentityApp(unittest.TestCase):\n    \"\"\"测试身份应用\"\"\"\n    \n    def test_get_identity(self):\n        \"\"\"测试身份描述函数\"\"\"\n        identity = get_identity()\n        self.assertIsNotNone(identity)\n        self.assertIsInstance(identity, str)\n        self.assertGreater(len(identity), 0)\n        self.assertIn(\"AI助手\", identity)\n    \n    def test_main_returns_zero(self):\n        \"\"\"测试主函数返回0\"\"\"\n        result = main()\n        self.assertEqual(result, 0)\n    \n    def test_identity_contains_keywords(self):\n        \"\"\"测试身份描述包含关键词\"\"\"\n        identity = get_identity()\n        keywords = [\"AI\", \"助手\", \"帮助\", \"解答\"]\n        for keyword in keywords:\n            self.assertIn(keyword, identity, f\"身份描述应包含关键词: {keyword}\")\n\nclass TestConfig(unittest.TestCase):\n    \"\"\"测试配置模块\"\"\"\n    \n    def test_load_config_defaults(self):\n        \"\"\"测试加载默认配置\"\"\"\n        from config import load_config\n        config = load_config()\n        self.assertIn(\"app_name\", config)\n        self.assertIn(\"version\", config)\n        self.assertIn(\"verbose\", config)\n        self.assertEqual(config[\"app_name\"], \"IdentityApp\")\n    \n    def test_config_has_language(self):\n        \"\"\"测试配置包含语言设置\"\"\"\n        from config import load_config\n        config = load_config()\n        self.assertIn(\"language\", config)\n        self.assertEqual(config[\"language\"], \"zh-CN\")\n\nif __name__ == \"__main__\":\n    unittest.main(verbosity=2)\n"
    },
    {
      "path": "README.md",
      "content": "# IdentityApp - 我是做什么的\n\n## 项目简介\n\n这是一个简单的Python应用程序，用于回答“你是做什么的”这个问题。程序会输出AI助手的身份描述。\n\n## 功能特点\n\n- 输出AI助手的身份描述\n- 支持配置文件管理\n- 包含单元测试\n- 支持详细模式输出\n\n## 安装说明\n\n### 环境要求\n\n- Python 3.6+\n- 无需额外依赖\n\n### 安装步骤\n\n1. 克隆或下载项目文件\n2. 进入项目目录\n\n## 使用方法\n\n### 运行主程序\n\n